test

diff --git a/.github/workflows/change-log.yml b/.github/workflows/change-log.yml
--- a/.github/workflows/change-log.yml
+++ b/.github/workflows/change-log.yml
@@ -19,10 +19,12 @@ jobs:
       #      echo "Error: CHANGELOG.md has not been modified. Please update the Changelog file."
       #      exit 1
       #    fi
-      - name: Verify Changelog Has Meaningful Changes
+      - name: Verify CHANGELOG.md is Modified
         run: |
-          git diff --name-only
-          if git diff --exit-code CHANGELOG.md; then
-            echo "Error: CHANGELOG.md must have meaningful changes."
+          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
+          echo "Changed files: $CHANGED_FILES"
+
+          if ! echo "$CHANGED_FILES" | grep -q 'CHANGELOG.md'; then
+            echo "::error::The file 'CHANGELOG.md' must be updated for this pull request."
             exit 1
           fi
