feat(XAAS-1111): changed release-drafter format     * added pr title check

diff --git a/.github/workflows/validate-pr.yaml b/.github/workflows/validate-pr.yaml
--- a/.github/workflows/validate-pr.yaml
+++ b/.github/workflows/validate-pr.yaml
@@ -47,8 +47,8 @@ jobs:
           echo "Commit messages fetched: $COMMITS"
 
             if [ -z "$COMMITS" ]; then
-            echo "No commit messages found."
-            exit 1
+              echo "No commit messages found."
+              exit 1
             fi
 
             JIRA_IDS=()
@@ -60,8 +60,8 @@ jobs:
             if echo "$COMMIT" | grep -qE '[xX][aA][aA][sS][pP]?-[0-9]+'; then
                 NEW_ID=$(echo "$COMMIT" | grep -oE '[xX][aA][aA][sS][pP]?-[0-9]+')
                 if [[ ! " ${JIRA_IDS[@]} " =~ " ${NEW_ID} " ]]; then
-                JIRA_IDS+=("$NEW_ID")
-                echo "Found Jira ID: $NEW_ID"
+                   JIRA_IDS+=("$NEW_ID")
+                   echo "Found Jira ID: $NEW_ID"
                 fi
             fi
 
@@ -92,10 +92,15 @@ jobs:
             fi
             done
 
+            # TODO: Should we exit in this case?
             if [ ${#JIRA_IDS[@]} -eq 0 ]; then
-            echo "No Jira IDs found."
-            exit 1
+               echo "No Jira IDs found."
+               exit 1
             fi
+
+            #if [ "$JIRA_ID" = "" ]; then
+            #  JIRA_ID="N/A"
+            #fi
 
             UNIQUE_LABELS=($(echo "${LABELS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
 
@@ -111,9 +116,6 @@ jobs:
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
             -d "$LABELS_JSON"
-          if [ "$JIRA_ID" = "" ]; then
-            JIRA_ID="N/A"
-          fi
 
           echo "labels=$LABELS_JSON" >> $GITHUB_ENV
           echo "jira_id=$JIRA_IDS_JSON" >> $GITHUB_ENV
@@ -157,3 +159,39 @@ jobs:
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER \
             -d "$(jq -nc --arg body "$UPDATED_BODY" '{body: $body}')"
+
+
+  validate-pr-title:
+    name: Validate PR Title
+    runs-on: ubuntu-latest
+    needs: [validate-commits-and-branch, label]
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v3
+
+      - name: Set up GitHub CLI
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: echo "GitHub CLI is authenticated using GH_TOKEN"
+
+      - name: Validate PR Title Format
+        if: env.jira_id != 'N/A'
+        env:
+          PR_NUMBER: ${{ github.event.pull_request.number }}
+          JIRA_IDS: ${{ env.jira_id }}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          echo "Validating PR title format..."
+
+          # Fetch current PR title
+          PR_TITLE=$(gh pr view $PR_NUMBER --json title -q ".title")
+
+          if [[ ! "$PR_TITLE" =~ ^(feat|bugfix|docs|refactor|test|chore)\([a-zA-Z0-9_-]+\):\ [a-zA-Z].+ ]]; then
+            echo -e "ERROR: ❌ PR title does not follow semantic format.
+                      Expected format: <type>(<jiraissue>): <subject>
+                      Example: feat(XAAS-12345): add new feature
+                      Allowed types: feat, bugfix, docs, refactor, test, chore"
+            exit 1
+          else
+            echo "PR title format is valid."
+          fi
